# Auto-extracted localization strings

TEXTS = {
 "fa": {
 "welcome_bonus": "**به صرافی CX خوش آمدید!**\nمبلغ ۵ TON بونوس راه‌اندازی به کیف پول شما اضافه شد.",
 "mandatory_phone_msg": "**تایید شماره موبایل (الزامی)**\nجهت حفظ امنیت و مطابقت با استانداردهای بین‌المللی AML، شماره موبایل خود را تایید کنید:",
 "btn_send_phone": "تایید و ارسال شماره",
 "phone_saved_msg": "شماره موبایل با موفقیت در هسته امنیتی صرافی ثبت شد.",
 "kyc_decision_msg": "**وضعیت حساب: استاندارد (سطح ۱)**\nبرای ارتقا به سطح ۲ و دسترسی به سقف برداشت نامحدود، ارسال ایمیل رسمی و تصویر مدارک شناسایی الزامی است.",
 "btn_upgrade_kyc": "تکمیل احراز هویت (سطح ۲)",
 "btn_skip_kyc": "ورود به داشبورد",
 "dashboard_ready": "به داشبورد معاملاتی **صرافی CX** خوش آمدید:",
 "limit_feature": "این قابلیت نیازمند حساب تأییدشده سطح ۲ است.",
 "trade_section": "بخش معاملات صرافی CX:",
 "finance_section": "بخش امور مالی و مدیریت سرمایه:",
 "rewards_section": "خدمات ویژه، پاداش‌ها و رویدادها:",
 "settings_section": "تنظیمات امنیتی و پروفایل کاربری:",
 "binary_title": "**مرکز معاملات باینری آپشن CX**\nموجودی نقد: `{0:g} TON`",
 "btn_launch_trade": "ورود به ترید",
 "sniper_title": "**بازی معاملاتی اسنایپر تیک‌چارت**",
 "btn_launch_game": "شروع شکار",
 "prop_active": "**حساب پراپ تریدینگ فعال**\nسایز حساب: `{0:,.0f} TON` | بالانس: `{1:,.2f} TON`",
 "prop_lobby": "**لابی چالش‌های پراپ صرافی CX**\nموجودی ولت: `{0:g} TON`",
 "btn_launch_term": "ترمینال معاملاتی",
 "btn_prop_10k": "چالش 10,000 TON (هزینه: 50 TON)",
 "btn_prop_50k": "چالش 50,000 TON (هزینه: 200 TON)",
 "prop_success": "چالش پراپ فعال گردید.",
 "insufficient_bal": "موجودی کیف پول کافی نیست!",
 "staking_desc": "**صندوق استیکینگ و تأمین نقدینگی CX**",
 "btn_stake_7": "استیک ۷ روزه (APY 5%)",
 "btn_stake_30": "استیک ۳۰ روزه (APY 12%)",
 "btn_stake_90": "استیک ۹۰ روزه (APY 25%)",
 "stake_enter_amt": "مبلغ سپرده‌گذاری ({0} روزه) را وارد کنید:",
 "stake_invalid": "مبلغ نامعتبر است.",
 "stake_success": "استیک ثبت شد. تاریخ آزادسازی: {1}",
 "loan_active": "شما وام تسویه‌نشده به مبلغ `{0:g} TON` دارید. برداشت مسدود است.",
 "loan_desc": "**وام آنی بدون وثیقه (CX Flash Loan)**\nدریافت: 20 TON | بازپرداخت: 24 TON",
 "btn_loan_accept": "دریافت فوری وام",
 "loan_exists": "شما از قبل وام فعال دارید!",
 "loan_success": "وام به کیف پول واریز شد.",
 "vip_active": "شما کاربر VIP هستید.\nانقضا: `{0}`",
 "vip_desc": "**اشتراک ویژه (VIP Premium)**",
 "btn_vip_1m": "۱ ماهه (2 TON)",
 "btn_vip_3m": "۳ ماهه (6 TON)",
 "btn_vip_6m": "۶ ماهه (10 TON)",
 "btn_vip_1y": "۱ ساله (15 TON)",
 "btn_vip_life": "دائمی (35 TON)",
 "vip_success": "حساب شما به وضعیت VIP ارتقا یافت.",
 "predict_desc": "**استخر پیش‌بینی ۱ ساعته**\nورود: 5 TON | پاداش برد: 9 TON",
 "btn_pred_btc_up": "بیت‌کوین صعودی", "btn_pred_btc_down": "بیت‌کوین نزولی",
 "btn_pred_gold_up": "انس طلا صعودی", "btn_pred_gold_down": "انس طلا نزولی",
 "predict_err_server": "خطا در دریافت نرخ بازار.",
 "predict_wait": "پیش‌بینی روی **{0} {1}** ثبت گردید.",
 "predict_win": "**پیش‌بینی موفق!**\nمبلغ 9 TON واریز شد.",
 "predict_loss": "پیش‌بینی ناموفق بود.",
 "btn_pred_new": "پیش‌بینی جدید",
 "mission_desc": "**مرکز تسک‌های پاداش‌دار**\n\nبا انجام ماموریت‌های زیر، موجودی خود را افزایش دهید:",
 "btn_miss_ch": "{0} عضویت در کانال (2 TON)",
 "btn_miss_yt": "{0} کوییز یوتیوب (3 TON)",
 "btn_miss_inv": "{0} بررسی پاداش دعوت (5 TON)",
 "yt_quiz_title": "سطحی که بیشترین حجم بازار در آن متمرکز شده چیست؟",
 "miss_claimed": "این پاداش قبلاً دریافت شده است!",
 "miss_ch_success": "پاداش کانال واریز شد.",
 "miss_ch_err": "عضویت در کانال تایید نشد!",
 "miss_yt_success": "پاسخ صحیح بود! پاداش واریز شد.",
 "miss_yt_err_burn": "پاسخ نادرست بود! فرصت پاداش سوخت.",
 "miss_inv_success": "پاداش دعوت واریز شد.",
 "miss_inv_err": "تعداد دعوت‌ها کافی نیست ({0}/3).",
 "checking_net": "در حال استعلام نودهای بلاک‌چین TON...",
 "err_dep_api": "اختلال موقت در ارتباط با شبکه.",
 "dep_auto_success": "تراکنش تأیید شد و مبلغ `{0:g} TON` شارژ گردید.",
 "dep_not_found": "تراکنشی با شناسه (Memo) `{0}` روی شبکه یافت نشد.",
 "with_blocked": "وام فعال مانع خروج دارایی است.",
 "with_addr_ask": "آدرس مقصد برداشت در شبکه TON را ارسال کنید:\n(حداقل: 150 TON)",
 "err_with_min": "حداقل مبلغ برداشت 150 TON می‌باشد.",
 "with_amt_ask": "مبلغ برداشت را وارد کنید:",
 "req_submitted": "درخواست شما ثبت و در صف پردازش قرار گرفت.",
 "btn_cat_trade": "معاملات", "btn_cat_finance": "امور مالی",
 "btn_cat_rewards": "پاداش و خدمات ویژه", "btn_cat_settings": "تنظیمات",
 "btn_back_main": "بازگشت به منوی اصلی", "btn_binary": "باینری آپشن CX",
 "btn_prop": "پراپ تریدینگ", "btn_sniper": "بازی اسنایپر",
 "btn_deposit_withdraw": "واریز / برداشت", "btn_transfer": "انتقال P2P",
 "btn_wallet": "کیف پول من", "btn_staking": "صندوق استیکینگ",
 "btn_loan": "وام فلش", "btn_daily_bonus": "گردونه شانس (بونوس)",
 "btn_vip": "اشتراک VIP", "btn_predict": "استخر پیش‌بینی",
 "btn_missions": "مرکز ماموریت‌ها", "btn_profile": "پروفایل",
 "btn_lang": "تغییر زبان", "btn_cancel": "لغو", "cancelled": "عملیات لغو شد.",
 "btn_admin_panel": "پنل مدیریت",
 "online_msg": "**سیستم معاملاتی آنلاین شد**\n\nهسته معاملاتی صرافی CX با موفقیت راه‌اندازی و بروزرسانی شد. هم‌اکنون تمامی بازارها و خدمات مالی در دسترس می‌باشند. ",
 "maintenance_msg": "**بروزرسانی هسته معاملاتی**\n\nکاربر گرامی، سرورهای صرافی CX جهت ارتقای زیرساخت امنیتی و بهبود سرعت معاملات، موقتاً از دسترس خارج شدند. از شکیبایی شما سپاسگزاریم.",
 "kyc_upload_ask": "لطفاً یک تصویر شفاف از کارت ملی یا پاسپورت خود ارسال کنید:",
 "kyc_pending_new": "مدارک ثبت شد و در صف تأیید قرار گرفت.",
 "btn_miniapp_dash": "ورود به مینی‌اپ صرافی (DApp)",
 "transfer_desc": "شناسه عددی (User ID) دریافت‌کننده را وارد کنید:",
 "transfer_amt_ask": "مبلغ انتقال را به TON وارد کنید:",
 "transfer_err_notfound": "حساب کاربری مقصد یافت نشد.",
 "transfer_err_self": "امکان انتقال به خود وجود ندارد.",
 "transfer_success": "مبلغ `{0:g} TON` با موفقیت انتقال یافت.",
 "transfer_received": "مبلغ `{0:g} TON` از طرف شناسه `{1}` به حسابتان واریز شد.",
 "bonus_wait": "هر ۲۴ ساعت یک بار مجاز به چرخش گردونه هستید.",
 "spin_wheel_win": "گردونه متوقف شد! شما برنده `{0} TON` پاداش شدید. ",
 "btn_support": "پشتیبانی آنلاین",
 "btn_swap": "سواپ (Swap)",
 "btn_security": "مرکز امنیت حساب",
 "btn_pnl": "کارت سود من (P&L)",
 "ask_pin_setup": "لطفاً یک پین‌کد ۴ رقمی برای تایید تراکنش‌های مالی تعریف کنید:",
 "pin_saved": "پین امنیتی ۴ رقمی شما با موفقیت فعال گردید.",
 "ask_pin_verify": "برای تأیید نهایی، پین‌کد ۴ رقمی خود را وارد کنید:",
 "wrong_pin": "پین امنیتی واردشده نادرست است!",
 "freeze_active": "سیستم مالی در حالت توقف اضطراری قرار دارد. لطفاً بعداً تلاش کنید.",
 "cooldown_error": "به دلیل تغییرات امنیتی اخیر، حساب شما تا ۲۴ ساعت در حالت قفل برداشت است.",
 "whitelist_ask": "آدرس ولت اختصاصی خود در Tonkeeper را برای اضافه شدن به لیست سفید ارسال کنید:",
 "whitelist_saved": "آدرس شما در لیست سفید امنیتی ثبت شد.",
 "kyc_ask_email": "جهت آغاز احراز هویت، لطفاً آدرس ایمیل معتبر خود را وارد کنید:",
 "email_invalid": "فرمت ایمیل نامعتبر است یا از ایمیل‌های موقت استفاده شده است!",
 "support_title": "**مرکز پشتیبانی و پایگاه دانش صرافی CX**\n\nجهت دریافت راهنمایی، سوالات متداول را مطالعه نموده یا مستقیماً به پشتیبان پیام دهید:",
 "support_ask": "پیام یا گزارش فنی خود را برای تیم پشتیبانی ارسال کنید:",
 "support_sent": "پیام شما ثبت شد. پاسخ از طریق همین ربات برای شما ارسال خواهد شد."
 },
 "en": {
 "welcome_bonus": "**Welcome to CX Exchange!**\n5 TON initial bonus has been credited.",
 "mandatory_phone_msg": "**Phone Verification Required**\nPlease verify your phone number to comply with AML standards:",
 "btn_send_phone": "Verify Phone",
 "phone_saved_msg": "Phone number verified.",
 "kyc_decision_msg": "**Account Status: Standard (Level 1)**\nUpgrade to Level 2 for unrestricted operations.",
 "btn_upgrade_kyc": "Complete KYC (Level 2)",
 "btn_skip_kyc": "Proceed to Dashboard",
 "dashboard_ready": "Welcome to **CX Exchange** Terminal:",
 "limit_feature": "Level 2 verification required.",
 "trade_section": "Trading Terminal:",
 "finance_section": "Financial Hub:",
 "rewards_section": "VIP & Reward Hub:",
 "settings_section": "Security & Profile:",
 "binary_title": "**CX Binary Trading Center**\nBalance: `{0:g} TON`",
 "btn_launch_trade": "Trade Now",
 "sniper_title": "**Tick Chart Sniper Engine**",
 "btn_launch_game": "Start Sniper",
 "prop_active": "**Active Prop Account**\nSize: `{0:,.0f} TON` | Balance: `{1:,.2f} TON`",
 "prop_lobby": "**CX Prop Trading Challenges**\nWallet Balance: `{0:g} TON`",
 "btn_launch_term": "Open Terminal",
 "btn_prop_10k": "10k Challenge (Fee: 50 TON)",
 "btn_prop_50k": "50k Challenge (Fee: 200 TON)",
 "prop_success": "Prop challenge activated.",
 "insufficient_bal": "Insufficient balance!",
 "staking_desc": "**CX Staking & Liquidity Vault**",
 "btn_stake_7": "7 Days (APY 5%)",
 "btn_stake_30": "30 Days (APY 12%)",
 "btn_stake_90": "90 Days (APY 25%)",
 "stake_enter_amt": "Enter lock amount for {0} days:",
 "stake_invalid": "Invalid amount.",
 "stake_success": "Staked successfully. Release date: {1}",
 "loan_active": "Active loan of `{0:g} TON` is blocking withdrawals.",
 "loan_desc": "**Instant Uncollateralized Flash Loan**\nBorrow: 20 TON | Repay: 24 TON",
 "btn_loan_accept": "Accept Terms & Borrow",
 "loan_exists": "Active loan already exists!",
 "loan_success": "Loan credited to wallet.",
 "vip_active": "VIP status active.\nExpires: `{0}`",
 "vip_desc": "**VIP Premium Subscription**",
 "btn_vip_1m": "1 Month (2 TON)",
 "btn_vip_3m": "3 Months (6 TON)",
 "btn_vip_6m": "6 Months (10 TON)",
 "btn_vip_1y": "1 Year (15 TON)",
 "btn_vip_life": "Lifetime (35 TON)",
 "vip_success": "Account upgraded to VIP.",
 "predict_desc": "**1-Hour Prediction Pool**\nEntry: 5 TON | Reward: 9 TON",
 "btn_pred_btc_up": "BTC Bullish", "btn_pred_btc_down": "BTC Bearish",
 "btn_pred_gold_up": "Gold Bullish", "btn_pred_gold_down": "Gold Bearish",
 "predict_err_server": "Error fetching market feeds.",
 "predict_wait": "Prediction set on **{0} {1}**.",
 "predict_win": "**Accurate Prediction!**\n9 TON credited.",
 "predict_loss": "Prediction failed.",
 "btn_pred_new": "New Prediction",
 "mission_desc": "**Task-to-Earn Center**",
 "btn_miss_ch": "{0} Channel Task (2 TON)",
 "btn_miss_yt": "{0} YouTube Task (3 TON)",
 "btn_miss_inv": "{0} Referral Task (5 TON)",
 "yt_quiz_title": "Which level concentrated the most trading volume?",
 "miss_claimed": "Task already completed!",
 "miss_ch_success": "Reward credited.",
 "miss_ch_err": "Channel membership not verified!",
 "miss_yt_success": "Correct! Reward credited.",
 "miss_yt_err_burn": "Wrong answer! Reward burned.",
 "miss_inv_success": "Referral reward credited.",
 "miss_inv_err": "Not enough referrals ({0}/3).",
 "checking_net": "Scanning TON nodes...",
 "err_dep_api": "Network communication error.",
 "dep_auto_success": "Verified! Credited `{0:g} TON`.",
 "dep_not_found": "No deposit found with memo `{0}`.",
 "with_blocked": "Active loan blocks withdrawals.",
 "with_addr_ask": "Send your Tonkeeper wallet address:\n(Min: 150 TON)",
 "err_with_min": "Minimum withdrawal is 150 TON.",
 "with_amt_ask": "Enter withdrawal amount:",
 "req_submitted": "Request queued for security processing.",
 "btn_cat_trade": "Trade", "btn_cat_finance": "Finance",
 "btn_cat_rewards": "Rewards", "btn_cat_settings": "Settings",
 "btn_back_main": "Main Menu", "btn_binary": "CX Binary",
 "btn_prop": "Prop Trading", "btn_sniper": "Sniper Game",
 "btn_deposit_withdraw": "Deposit / Withdraw", "btn_transfer": "P2P Transfer",
 "btn_wallet": "My Wallet", "btn_staking": "Staking Vault",
 "btn_loan": "Flash Loan", "btn_daily_bonus": "Lucky Wheel",
 "btn_vip": "VIP Tier", "btn_predict": "Prediction Pool",
 "btn_missions": "Missions", "btn_profile": "Profile",
 "btn_lang": "Language", "btn_cancel": "Cancel", "cancelled": "Operation cancelled.",
 "btn_admin_panel": "Admin Hub",
 "online_msg": "**System Online**\n\nCX Exchange core systems have been successfully updated and are fully operational. ",
 "maintenance_msg": "**System Maintenance**\n\nCX Exchange servers are currently undergoing core infrastructure upgrades. Thank you for your patience.",
 "kyc_upload_ask": "Please upload a clear photo of your ID/Passport:",
 "kyc_pending_new": "Documents queued for validation.",
 "btn_miniapp_dash": "Launch Exchange DApp",
 "transfer_desc": "Enter recipient numeric User ID:",
 "transfer_amt_ask": "Enter transfer amount in TON:",
 "transfer_err_notfound": "Recipient account not found.",
 "transfer_err_self": "Cannot transfer to self.",
 "transfer_success": "Transferred `{0:g} TON` successfully.",
 "transfer_received": "Received `{0:g} TON` from user `{1}`.",
 "bonus_wait": "Lucky Wheel is available once every 24 hours.",
 "spin_wheel_win": "Wheel stopped! You won `{0} TON`. ",
 "btn_support": "Support & Helpdesk",
 "btn_swap": "CX Swap",
 "btn_security": "Security Hub",
 "btn_pnl": "P&L Share Card",
 "ask_pin_setup": "Define a 4-digit security PIN for transaction authorizations:",
 "pin_saved": "Security PIN activated.",
 "freeze_active": "Exchange operations are temporarily frozen for maintenance.",
 "whitelist_ask": "Send your Tonkeeper address to whitelist:",
 "whitelist_saved": "Address whitelisted successfully.",
 "kyc_ask_email": "Enter your official email address to proceed:",
 "email_invalid": "Invalid or disposable email address rejected!",
 "support_title": "**CX Exchange Help Center**\nBrowse FAQs or contact direct live support:",
 "support_ask": "Please describe your inquiry:",
 "support_sent": "Support ticket created. We will reply via bot."
 }
}

FAQ_DATA = {
 "faq_deposit": {
 "title_fa": "واریز و ممو",
 "title_en": "Deposit & Memo",
 "ans_fa": "**راهنمای واریز به صرافی CX:**\nتمامی واریزها در شبکه TON باید منحصراً از کیف‌پول **Tonkeeper** انجام شود. حتماً شناسه عددی اکانت خود را در بخش **Comment / Memo** وارد کنید تا واریز به صورت خودکار شناسایی شود. حداقل واریز مجاز 40 TON است.",
 "ans_en": "**Deposit Policy:**\nAll deposits must be executed via **Tonkeeper** on TON Mainnet. Always enter your numeric Telegram ID in the **Comment / Memo** field. Minimum deposit is 40 TON."
 },
 "faq_withdraw": {
 "title_fa": "شرایط و زمان برداشت",
 "title_en": "Withdrawals",
 "ans_fa": "**قوانین خروج دارایی:**\nحداقل مبلغ برداشت 150 TON است. تا زمان تسویه وام فلش امکان برداشت وجود ندارد. همچنین در صورت تغییر پین یا ولت لیست سفید، برداشت تا ۲۴ ساعت قفل خواهد بود.",
 "ans_en": "**Withdrawal Policy:**\nMinimum withdrawal is 150 TON. Settle active flash loans first. 24h security lock applies on PIN or whitelist changes."
 },
 "faq_kyc": {
 "title_fa": "احراز هویت (KYC)",
 "title_en": "KYC Levels",
 "ans_fa": "**سطوح کاربری صرافی:**\nسطح ۱ بلافاصله پس از تایید شماره تماس فعال می‌گردد. برای ارتقا به سطح ۲ (فول اکسس و نامحدود)، ثبت ایمیل دائمی رسمی و ارسال تصویر کارت ملی یا پاسپورت الزامی است.",
 "ans_en": "**Verification:**\nLevel 1 activates on phone verification. Level 2 unlocks unlimited limits upon official email and ID photo verification."
 },
 "faq_prop": {
 "title_fa": "چالش‌های پراپ",
 "title_en": "Prop Challenges",
 "ans_fa": "**سیستم پراپ تریدینگ:**\nبا پرداخت ورودی چالش، نقدینگی مجازی در مینی‌اپ در اختیارتان قرار می‌گیرد. با رسیدن به تارگت سود بدون نقض حد ضرر، سهم سود نقدی دریافت خواهید کرد.",
 "ans_en": "**Prop Engine:**\nPay the challenge fee to access simulated terminal capital. Reach the target profit without drawdown breach to withdraw profit share."
 }
}
